name: "Base Branch Test"

on:
  push:
    branches:
      - master

extends:
  - .github/workflows/test-workflow-template.yml

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [ test, integration-tests ]
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        run: echo "Creating release"
