name: "Base Branch Test"

on:
  push:
    branches:
      - master

jobs:
  test-workflow:
    uses: ./.github/workflows/test-template.yml

  slack-notification:
    runs-on: ubuntu-latest
    name: Slack notification about job failure
    if: ${{ failure() }}
    needs: [ test-workflow ]
    steps:
      - name: Slack notification
        run: echo "Slack notification ${{ github.job }}"

  release:
    runs-on: ubuntu-latest
    needs: [ test-workflow ]
    steps:
      - uses: actions/checkout@v1
      - name: Create release
        run: echo "Creating release"
