---
name: "Run tests"
description: "A workflow for running tests on pull requests and pushes to master"
run-name: "${{ github.event.inputs.name }}"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: list files
        run: ls -al
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install dependencies
        run: go get . && go install github.com/mfridman/tparse@latest
      - name: Run tests
        run: go test -race -coverprofile=coverage_unit.txt ./example2/...  -json | tee gotest.json | tparse -follow
      - name: Process test results
        uses: robherley/go-test-action@v0
        with:
          fromJSONFile: ./gotest.json

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: list files
        run: ls -al
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install dependencies
        run: go get . && go install github.com/mfridman/tparse@latest
      - name: Run tests
        run: go test -race -coverprofile=coverage_unit.txt ./example3/...  -json | tee gotest.json | tparse -follow
      - name: Process test results
        uses: robherley/go-test-action@v0
        with:
          fromJSONFile: ./gotest.json