---
name: "Run tests"
description: "A workflow for running tests on pull requests and pushes to master"
run-name: "${{ github.event.inputs.name }}"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: list files
        run: ls -al
      - name: long running command
        run: for i in {1..10}; do date && sleep 1; done
      - name: create file
        run: echo "example" > test.txt

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: list files
        run: env | grep "GITHUB"
      - name: long running command
        run: for i in {1..10}; do date && sleep 1; done
      - name: create file
        run: echo "example" > integration-test.txt
      - name: fail the job
        run: .github/workflows/run.sh "${{github.run_attempt}}"